config/routes.rb
Rails.application.routes.draw do

  root 'sessions#login'

  get 'logout' => "sessions#destroy", :as => 'logout'
   get 'login' => "sessions#new", :as => 'login'
   post 'login' => "sessions#create"

  resources :users do
    get '/tasks/index' => "tasks#index", as: 'tasks'
    post '/tasks' => "tasks#create", as: 'create_task'
    post '/tasks/:id' => "tasks#update", as: 'update_task'
    delete '/tasks/:id' => "tasks#destroy", as: 'destroy_task'
  end

namespace :api, defaults: { format: 'json' } do
  namespace :v1 do
    resources :tasks, only: [:index, :create, :update, :destroy]
  end
end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tasks, dependent: :destroy

  validates :username, presence: true
  validates :password, length: { minimum: 6 }
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < ApplicationController
      protect_from_forgery with: :null_session
      respond_to :json

      def index
        respond_with Task.all
      end

      def create
        task = Task.create(params[:task])
        p "task: #{task}"
        if task
          render json: task
        else
          respond_with Task.all
        end
      end

      def update
        task = Task.update(current_user.id, params[:task])
        render json: task
      end

      def destroy
        Task.destroy(params[:id])
        respond_with Task.all
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # helper_method :current_user

  private

  def current_user
   @user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def login(user)
   session[:user_id] = user.id
  end

  def logout!
   session[:user_id] = nil
  end

  def find_user
   @user ||= User.find_by(username: params[:username])
  end

  def bounce
    if current_user
      redirect_to user_tasks_path(current_user)
    else
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if session[:user_id]
      redirect_to "/users/#{session[:user_id]}/tasks/index"
    else
      render "new"
    end
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @task = Task.new
    @tasks = Task.where(user: @user)

    respond_to do |format|
      format.html
      format.json { render :json => @tasks.to_json }
    end

  end

  def create
    @user = User.find(params[:user_id])
    @task = Task.create(user: @user, content: params[:task][:content], completed: false)
    redirect_to root_path
  end

  def update
    @task = Task.find(params[:id])
    new_status = !@task.completed
    @task.update(completed: new_status)
    redirect_to root_path
  end

  def destroy
    @task = Task.find_by(id:params[:id])
    p "to destroy: #{@task}"
    Task.destroy(@task.id)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # assumes whoever is creating user is also logging in as said user

    if User.find_by(username: user_params[:username])
      flash.now.alert = "That username is taken"
    elsif @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash.now.alert = "Invalid data"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])

    if session[:user_id] != @user.id
      redirect_to users_path
    else
      @user.destroy
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<div class="container">
    <h1>DO ALL THE THINGS</h1>
    <div>
        <%= form_for([@user, @task], url: user_create_task_path, method: "post") do |f| %>
            <%= f.text_field :content, placeholder: "What needs to be done?", size: 60 %>
            <% f.submit %>
        <% end %>
    </div>
    <table class="todo-list">
    <% @tasks.each do |task| %>
    <tr>
        <% if task.completed %>
              <td><strike><%= task.content %></strike></td>
        <% else %>
              <td><%= task.content %></td>
        <% end %>
        <td><%= button_to "toggle", user_update_task_path(@user, task) %></td>
        <td><%= button_to "delete", user_destroy_task_path(@user, task), method: "delete" %></td>
    </tr>
    <% end %>
    </table>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.username %></h1>

<%= render "form" %>

<%= button_to "Delete User", user_path(@user), method: "delete", data: { confirm: "Are you sure you want to delete #{@user.username}?" } %>

<%= link_to @user.username, user_path(@user) %><br>
<%= link_to "Users", users_path %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= link_to user.username, user_path(user) %></p>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form" %>

<%= link_to "Users", users_path %>

app/views/users/show.html.erb
<p><%= @user.username %><br><%= @user.email %></p>
<%= link_to "Edit", edit_user_path(@user) %><br>
<%= link_to "Users", users_path %>